apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: atas-cluster
  region: us-east-2
  version: "1.28"

vpc:
  cidr: 10.0.0.0/16

managedNodeGroups:
- name: dev-node
  amiFamily: AmazonLinux2
  instanceType: t2.micro
  desiredCapacity: 2
  ssh:
    publicKeyName: bkob-linux-ohio
