apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nginx-deployment
  labels:
    app_name: sample-httpd-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app_name: sample-httpd-server
  template:
    metadata:
      labels:
        app_name: sample-httpd-server
    spec:
      containers:
      - name: sample-httpd-server
        image: nbharathkumara/atas-demo  #nbharathkumara/atas-demo, nginx
        ports:
        - containerPort: 80
